export const GET_CARS = 'GET_CARS';
export const API_CARS_REQUEST = 'API_CARS_REQUEST';
export const API_AVAILABILITY_REQUEST = 'API_AVAILABILITY_REQUEST';
export const API_CARS_SUCCESS = "API_CARS_SUCCESS";
export const API_AVAILABILITY_SUCCESS = "API_AVAILABILITY_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";